pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@6.2.1
  - npm install
  - ng build
  - mv dist/kendo-popup/* public/
  artifacts:
    paths:
    - public
  only:
  - master